---
- name: Extract artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu


    
- name: "run server"
  become: true
  shell: |
    cd /home/ubuntu/
    npm install -g npm-install-peers
    pm2 stop default
    pm2 start npm --start