---

- name: Copy artifact to EC2 Instance
  copy:
    src: artifact.tar.gz
    dest: ~/
- name: "Extract"
  become: true
  shell: |
    tar -xvzf ~/artifact.tar.gz

- name: "server"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm --start